[package]
name = "capella-reqif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaserde = "0.10.0"
yaserde_derive = "0.10.0"
chrono = "0.4.37"